const fs = require('fs');
const path = require('path');

const assetsDir = path.join(__dirname, '../public/assets');
const dataFile = path.join(__dirname, '../lib/asset-data.ts');

const categories = ['logos', 'posts', 'motion-graphics', 'memecoins'];
let assets = [];

categories.forEach(category => {
  const categoryDir = path.join(assetsDir, category);
  if (!fs.existsSync(categoryDir)) return;

  const files = fs.readdirSync(categoryDir);
  const filesWithStats = files.map(file => {
    return {
      name: file,
      mtime: fs.statSync(path.join(categoryDir, file)).mtimeMs
    };
  }).sort((a, b) => b.mtime - a.mtime);

  filesWithStats.forEach(({ name: file }) => {
    const ext = path.extname(file).toLowerCase();
    
    // Determine type
    let type = null;
    if (['.jpg', '.jpeg', '.png', '.gif', '.webp'].includes(ext)) type = 'image';
    if (['.mp4', '.webm', '.ogg', '.mov'].includes(ext)) type = 'video';
    
    // Treat .gif.mp4 as video (already covered by .mp4)

    if (type) {
      assets.push({
        id: `${category}-${file}`,
        category: category,
        type: type,
        url: `/assets/${category}/${file}`,
        title: file
      });
    }
  });
});

const tsContent = `// Automatically generated by scripts/organize-assets.js
export type Asset = {
  id: string;
  category: string;
  type: 'image' | 'video';
  url: string;
  title: string;
};

export const portfolioAssets: Asset[] = ${JSON.stringify(assets, null, 2)};
`;

fs.writeFileSync(dataFile, tsContent, 'utf8');
console.log(`Generated asset-data.ts with ${assets.length} items.`);
